package pizarrafiguras;

import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Luis Correa
 */
public class PanelPizarra extends javax.swing.JPanel {

    private final Figuras figuras;

    /**
     * Creates new form PanelPizarra
     */
    public PanelPizarra(Figuras figuras) {
        this.figuras = figuras;
        initComponents();
    }

    public void addEventos(OyenteFiguras oyente) {
        this.botonCirculo.addActionListener(oyente);
        this.botonEstrella.addActionListener(oyente);
        this.botonHexagono.addActionListener(oyente);
        this.botonRectangulo.addActionListener(oyente);
        this.botonTriangulo.addActionListener(oyente);
        this.botonAceptar.addActionListener(oyente);
        this.botonRelleno.addActionListener(oyente);
        this.botonContorno.addActionListener(oyente);
        this.botonArriba.addActionListener(oyente);
        this.botonAbajo.addActionListener(oyente);
        this.botonIzquierda.addActionListener(oyente);
        this.botonDerecha.addActionListener(oyente);
        this.botonRotar.addActionListener(oyente);

        this.botonRotar.setName("rotar");
        this.botonArriba.setName("arriba");
        this.botonAbajo.setName("abajo");
        this.botonIzquierda.setName("izquierda");
        this.botonDerecha.setName("derecha");
        this.botonCirculo.setName("circulo");
        this.botonEstrella.setName("estrella");
        this.botonHexagono.setName("hexagono");
        this.botonRectangulo.setName("rectangulo");
        this.botonTriangulo.setName("triangulo");
        this.botonAceptar.setName("aceptar");
        this.botonRelleno.setName("relleno");
        this.botonContorno.setName("borde");
        this.panelCentro.addEventos(oyente);
    }

    public String[] getCampos() {
        return new String[]{
            textAncho.getText().trim(),
            textAlto.getText().trim(),
            textAngulo.getText().trim()
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNorte = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        botonCirculo = new javax.swing.JButton();
        botonRectangulo = new javax.swing.JButton();
        botonEstrella = new javax.swing.JButton();
        botonTriangulo = new javax.swing.JButton();
        botonHexagono = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        etiquetaAncho = new javax.swing.JLabel();
        textAncho = new javax.swing.JTextField();
        etiquetaAlto = new javax.swing.JLabel();
        textAlto = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        panelCentro = new pizarrafiguras.Pizarron(figuras);
        PanelSur = new javax.swing.JPanel();
        botonArriba = new javax.swing.JButton();
        botonIzquierda = new javax.swing.JButton();
        botonDerecha = new javax.swing.JButton();
        botonAbajo = new javax.swing.JButton();
        textAngulo = new javax.swing.JTextField();
        botonRelleno = new javax.swing.JButton();
        panelVistaRelleno = new javax.swing.JPanel();
        botonContorno = new javax.swing.JButton();
        panelVistaContorno = new javax.swing.JPanel();
        botonRotar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        PanelNorte.setLayout(new java.awt.GridLayout(2, 0));

        panelBotones.setLayout(new java.awt.GridLayout(1, 5));

        botonCirculo.setText("Circulo");
        botonCirculo.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));
        panelBotones.add(botonCirculo);

        botonRectangulo.setText("Rectangulo");
        botonRectangulo.setToolTipText("");
        botonRectangulo.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));
        panelBotones.add(botonRectangulo);

        botonEstrella.setText("Estrella");
        botonEstrella.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));
        panelBotones.add(botonEstrella);

        botonTriangulo.setText("Triangulo");
        botonTriangulo.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));
        panelBotones.add(botonTriangulo);

        botonHexagono.setText("Hexagono");
        botonHexagono.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));
        panelBotones.add(botonHexagono);

        PanelNorte.add(panelBotones);

        etiquetaAncho.setText("Ancho:");

        etiquetaAlto.setText("Alto:");

        botonAceptar.setText("Aceptar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(etiquetaAncho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaAlto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(botonAceptar)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(textAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAlto)
                    .addComponent(textAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAncho))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        PanelNorte.add(jPanel2);

        add(PanelNorte, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout panelCentroLayout = new javax.swing.GroupLayout(panelCentro);
        panelCentro.setLayout(panelCentroLayout);
        panelCentroLayout.setHorizontalGroup(
            panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        panelCentroLayout.setVerticalGroup(
            panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        add(panelCentro, java.awt.BorderLayout.CENTER);

        botonArriba.setText("Arriba");
        botonArriba.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));

        botonIzquierda.setText("Izquierda");
        botonIzquierda.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));

        botonDerecha.setText("Derecha");
        botonDerecha.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));

        botonAbajo.setText("Abajo");
        botonAbajo.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 5));

        botonRelleno.setText("Relleno");

        javax.swing.GroupLayout panelVistaRellenoLayout = new javax.swing.GroupLayout(panelVistaRelleno);
        panelVistaRelleno.setLayout(panelVistaRellenoLayout);
        panelVistaRellenoLayout.setHorizontalGroup(
            panelVistaRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        panelVistaRellenoLayout.setVerticalGroup(
            panelVistaRellenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        botonContorno.setText("Contorno");

        javax.swing.GroupLayout panelVistaContornoLayout = new javax.swing.GroupLayout(panelVistaContorno);
        panelVistaContorno.setLayout(panelVistaContornoLayout);
        panelVistaContornoLayout.setHorizontalGroup(
            panelVistaContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        panelVistaContornoLayout.setVerticalGroup(
            panelVistaContornoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        botonRotar.setText("Rotar");

        javax.swing.GroupLayout PanelSurLayout = new javax.swing.GroupLayout(PanelSur);
        PanelSur.setLayout(PanelSurLayout);
        PanelSurLayout.setHorizontalGroup(
            PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSurLayout.createSequentialGroup()
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSurLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonIzquierda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonDerecha))
                    .addGroup(PanelSurLayout.createSequentialGroup()
                        .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSurLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(botonArriba))
                            .addGroup(PanelSurLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(botonAbajo)))
                        .addGap(54, 54, 54)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRotar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(textAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRelleno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonContorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSurLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelVistaContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSurLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(panelVistaRelleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        PanelSurLayout.setVerticalGroup(
            PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSurLayout.createSequentialGroup()
                .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSurLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelVistaRelleno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonRelleno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelVistaContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonContorno)))
                    .addGroup(PanelSurLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botonArriba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonDerecha)
                            .addComponent(botonIzquierda)
                            .addComponent(textAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRotar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAbajo)))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        add(PanelSur, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNorte;
    private javax.swing.JPanel PanelSur;
    private javax.swing.JButton botonAbajo;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonArriba;
    private javax.swing.JButton botonCirculo;
    private javax.swing.JButton botonContorno;
    private javax.swing.JButton botonDerecha;
    private javax.swing.JButton botonEstrella;
    private javax.swing.JButton botonHexagono;
    private javax.swing.JButton botonIzquierda;
    private javax.swing.JButton botonRectangulo;
    private javax.swing.JButton botonRelleno;
    private javax.swing.JButton botonRotar;
    private javax.swing.JButton botonTriangulo;
    private javax.swing.JLabel etiquetaAlto;
    private javax.swing.JLabel etiquetaAncho;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelBotones;
    private pizarrafiguras.Pizarron panelCentro;
    private javax.swing.JPanel panelVistaContorno;
    private javax.swing.JPanel panelVistaRelleno;
    private javax.swing.JTextField textAlto;
    private javax.swing.JTextField textAncho;
    private javax.swing.JTextField textAngulo;
    // End of variables declaration//GEN-END:variables

    public Pizarron getPanelCentro() {
        return panelCentro;
    }

    public JPanel getpanelVistaRelleno() {
        return panelVistaRelleno;
    }

    public JPanel getpanelVistaContorno() {
        return panelVistaContorno;
    }

    public JTextField gettextAlto() {
        return textAlto;
    }

}
